name = "varsha-ecommerce-web"
pages_build_output_dir = "."
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "varsha-db"
database_id = "1ba8d80f-443a-4530-907a-1aabe4cae813"
migrations_dir = "migrations"

# Optional: Cloudflare R2 bucket for furniture media assets
# [[r2_buckets]]
# binding = "IMAGES_BUCKET"
# bucket_name = "varsha-furniture-assets"
